name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build the app
        run: ./gradlew assembleDevDebug --no-daemon
